routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TimeEntryController;
use App\Http\Controllers\ReportController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('projects', ProjectController::class);
Route::resource('tasks', TaskController::class);
Route::resource('time-entries', TimeEntryController::class);
Route::get('reports', [ReportController::class, 'index'])->name('reports.index');
Route::post('reports/filter', [ReportController::class, 'filter'])->name('reports.filter');

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'status'];

    public function tasks()
    {
        return $this->hasMany(Task::class);
    }
}

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;
    protected $fillable = ['project_id', 'name', 'status'];

    public function project()
    {
        return $this->belongsTo(Project::class);
    }
    
    public function timeEntries()
    {
        return $this->hasMany(TimeEntry::class);
    }
}

app/Models/TimeEntry.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TimeEntry extends Model
{
    use HasFactory;
    protected $fillable = ['task_id', 'hours', 'date', 'description'];

    public function task()
    {
        return $this->belongsTo(Task::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;

class ProjectController extends Controller
{
    public function index()
    {
        
        $projects = Project::all();
        return view('projects.index', compact('projects'));
    }
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Support\Facades\View;
use Illuminate\Http\Request;

class ReportController extends Controller
{
   
    public function index()
    {
        $projects = Project::with('tasks.timeEntries')->get();
        return view('reports.index', compact('projects'));
    }

    public function filter(Request $request)
    {
        $projectId = $request->input('project_id');

        $projects = Project::when($projectId, function ($query) use ($projectId) {
            $query->where('id', $projectId);
        })->with('tasks.timeEntries')->get();

        $view = view::make('reports.report-content', ['projects' => $projects]);
        $content = $view->render();

        return response()->json(['content' => $content]);
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    public function index()
    {
    
        $tasks = Task::with('project')->get();
        return view('tasks.index', compact('tasks'));
    }
}

app/Http/Controllers/TimeEntryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use App\Models\TimeEntry;
use Illuminate\Http\Request;

class TimeEntryController extends Controller
{
     public function index()
    {
        
        $timeEntries = TimeEntry::with('task.project')->get();
        return view('time_entries.index', compact('timeEntries'));
    }
    public function create()
    {
        $tasks = Task::all();
        return view('time_entries.create', compact('tasks'));
    }

    public function store(Request $request)
    {

        $validatedData = $request->validate([
            'task_id' => 'required',
            'hours' => 'required|numeric',
            'date' => 'required|date',
            'description' => 'required',
        ]);
        //Time entry storeing
        TimeEntry::create($validatedData);

        return redirect()->route('time-entries.index')->with('success', 'Time entry added successfully');
    }
}

resources/views/layouts/app.blade.php
<!-- resources/views/layouts/app.blade.php -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Management System</title>
    <!-- Include your CSS stylesheets or CDN links here -->
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        header {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 1em;
        }

        nav {
            background-color: #555;
            color: white;
            padding: 1em;
        }

        nav a {
            color: white;
            text-decoration: none;
            margin: 0 10px;
        }

        section {
            margin: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
    </style>
</head>
<body>
    <header>
        <h1>Project Management System</h1>
    </header>

    <nav>
        <a href="{{ route('projects.index') }}">Manage Projects</a>
        <a href="{{ route('tasks.index') }}">Manage Tasks</a>
        <a href="{{ route('time-entries.index') }}">Time Entry</a>
        <!-- Add more navigation links as needed -->
    </nav>

    <section>
        @yield('content')
    </section>
</body>
</html>

resources/views/projects/index.blade.php
<!-- resources/views/projects/index.blade.php -->
@extends('layouts.app')

@section('content')
    <h2>Manage Projects</h2>
    <table>
        <thead>
            <tr>
                <th>SNo</th>
                <th>Project Name</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($projects as $project)
                <tr>
                    <td>{{ $loop->index + 1 }}</td>
                    <td>{{ $project->name }}</td>
                    <td>{{ $project->status }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/reports/index.blade.php
@extends('layouts.app')

@section('content')
    <h2>Project Time Report</h2>

    <form id="filterForm">
        @csrf
        <label for="projectFilter">Filter by Project:</label>
        <select name="project_id" id="projectFilter">
            <option value="">All Projects</option>
            @foreach ($projects as $project)
                <option value="{{ $project->id }}">{{ $project->name }}</option>
            @endforeach
        </select>
        <button type="button" onclick="filterReport()">Apply Filter</button>
    </form>


    <div id="reportContent">
        @include('reports.report-content', ['projects' => $projects])
    </div>


    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        function filterReport() {
            var projectId = document.getElementById('projectFilter').value;

            $.ajax({
                type: 'POST',
                url: '{{ route("reports.filter") }}',
                data: { project_id: projectId, _token: '{{ csrf_token() }}' },
                success: function (data) {
                    $('#reportContent').html(data.content);
                },
                error: function (error) {
                    console.error('Error: ', error);
                }
            });
        }
    </script>
@endsection

resources/views/reports/report-content.blade.php
@foreach ($projects as $project)
    <h3>{{ $project->name }}</h3>
    <table>
        <thead>
            <tr>
                <th>Task</th>
                <th>Total Hours</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($project->tasks as $task)
                <tr>
                    <td>{{ $task->name }}</td>
                    <td>{{ $task->timeEntries->sum('hours') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endforeach

resources/views/tasks/index.blade.php
<!-- resources/views/tasks/index.blade.php -->
@extends('layouts.app')

@section('content')
    <h2>Manage Tasks</h2>
    <table>
        <thead>
            <tr>
                <th>SNo</th>
                <th>Project Name</th>
                <th>Task Name</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($tasks as $task)
                <tr>
                    <td>{{ $loop->index + 1 }}</td>
                    <td>{{ $task->project->name }}</td>
                    <td>{{ $task->name }}</td>
                    <td>{{ $task->status }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/time_entries/create.blade.php
<!-- resources/views/time_entries/create.blade.php -->

@extends('layouts.app')

@section('content')
    <h2>Add New Time Entry</h2>
    
    <form action="{{ route('time-entries.store') }}" method="post">
        @csrf

        <div class="form-group">
            <label for="task_id">Task:</label>
            <select name="task_id" id="task_id" class="form-control" required>
                @foreach ($tasks as $task)
                    <option value="{{ $task->id }}">{{ $task->name }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="hours">Hours:</label>
            <input type="number" name="hours" id="hours" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="date">Date:</label>
            <input type="date" name="date" id="date" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="description">Description:</label>
            <textarea name="description" id="description" class="form-control" rows="3" required></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Add Time Entry</button>
    </form>
@endsection

resources/views/time_entries/index.blade.php
<!-- resources/views/time_entries/index.blade.php -->
@extends('layouts.app')

@section('content')
    <h2>Time Entry</h2>
    <table>
        <thead>
            <tr>
                <th>SNo</th>
                <th>Project Name</th>
                <th>Task Name</th>
                <th>Hours</th>
                <th>Date</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach($timeEntries as $timeEntry)
                <tr>
                    <td>{{ $loop->index + 1 }}</td>
                    <td>{{ $timeEntry->task->project->name }}</td>
                    <td>{{ $timeEntry->task->name }}</td>
                    <td>{{ $timeEntry->hours }}</td>
                    <td>{{ $timeEntry->date }}</td>
                    <td>{{ $timeEntry->description }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection